services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.prod
    container_name: py-twitch-prod
    volumes:
      - ./package:/app
      - /app/files/clips
      - /app/src/notebooks
      - /app/src/__pycache__
      - /app/src/.ipynb_checkpoints
    environment:
      - ENV=PROD