FROM python:3.9

WORKDIR /app

COPY ./package /app

COPY ./deploy/requirements.dev.txt requirements.dev.txt

RUN apt update &&\
    apt-get install -y cmake &&\
    apt-get install ffmpeg -y 

#Headless
RUN apt-get install -y wget bzip2 libxtst6 libgtk-3-0 libx11-xcb-dev libdbus-glib-1-2 libxt6 libpci-dev && rm -rf /var/lib/apt/lists/*

#RUN apt-get install build-essential -y &&\
#    apt-get install -y wget bzip2 libxtst6 libgtk-3-0 libx11-xcb-dev libdbus-glib-1-2 libxt6 libpci-dev &&\
#    rm -rf /var/lib/apt/lists/* 
# Update the package list and install Chromium and its dependencies
RUN apt-get update && \
    apt-get install -y \
    chromium \
    chromium-driver \
    --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN pip install -r requirements.dev.txt

EXPOSE 8000

CMD jupyter notebook --ip=0.0.0.0 --port=8000 --no-browser --allow-root --NotebookApp.token=''