FROM python:3.9

WORKDIR /app

COPY ./package /app

COPY ./deploy/requirements.prod.txt requirements.prod.txt


RUN apt update &&\
    apt install ffmpeg -y &&\
    apt-get install build-essential -y &&\
    apt-get install -y wget bzip2 libxtst6 libgtk-3-0 libx11-xcb-dev libdbus-glib-1-2 libxt6 libpci-dev &&\
    rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.prod.txt

CMD /usr/local/bin/python /app/package/src/main.py
