FROM python:3.9

WORKDIR /app

COPY ./package /app

COPY ./deploy/requirements.dev.txt requirements.dev.txt

RUN apt update &&\
    apt-get install ffmpeg -y 

RUN pip install -r requirements.dev.txt

EXPOSE 8000

CMD jupyter notebook --ip=0.0.0.0 --port=8000 --no-browser --allow-root --NotebookApp.token=''