FROM python:3.9-bullseye

WORKDIR /app

COPY ./package /app

COPY ./deploy/requirements.dev.txt requirements.dev.txt


RUN echo '\
    Acquire::Retries "100";\
    Acquire::https::Timeout "240";\
    Acquire::http::Timeout "240";\
    APT::Get::Assume-Yes "true";\
    APT::Install-Recommends "false";\
    APT::Install-Suggests "false";\
    Debug::Acquire::https "true";\
    ' > /etc/apt/apt.conf.d/99custom

RUN apt update \
    && apt-get install ffmpeg -y  \
    && apt-get install -y --no-install-recommends ca-certificates curl firefox-esr           \
    && rm -fr /var/lib/apt/lists/*                \
    && curl -L https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz | tar xz -C /usr/local/bin \
    && apt-get purge -y ca-certificates curl

RUN pip install -r requirements.dev.txt


EXPOSE 8000

CMD jupyter notebook --ip=0.0.0.0 --port=8000 --no-browser --allow-root --NotebookApp.token=''